<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="14" total="17" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-08T20:09:46Z" name="CHP TEST" finished-at="2021-02-08T20:28:33Z" duration-ms="1127219">
    <groups>
      <group name="chppe">
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chppe -->
      <group name="chparg">
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chparg -->
      <group name="chpmex">
        <method signature="LoginTest.loginUsingSaveUserName()[pri:6, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginUsingSaveUserName" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chpmex -->
      <group name="chpchile">
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chpchile -->
      <group name="chpbr">
        <method signature="LoginTest.loginUsingSaveUserName()[pri:6, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginUsingSaveUserName" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chpbr -->
      <group name="chpury">
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chpury -->
    </groups>
    <test started-at="2021-02-08T20:09:46Z" name="LoginTest" finished-at="2021-02-08T20:28:33Z" duration-ms="1127219">
      <class name="com.trgr.quality.maf.tests.LoginTest">
        <test-method is-config="true" signature="setup(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" started-at="2021-02-08T17:09:42Z" name="setup" finished-at="2021-02-08T17:09:46Z" duration-ms="3464" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[qc]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chpbr]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" started-at="2021-02-08T17:09:46Z" name="beforeClass" finished-at="2021-02-08T17:09:46Z" duration-ms="5" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" started-at="2021-02-08T17:09:46Z" name="loginWithValidAndInvalidCredentials" description="MAFQABANG-32" finished-at="2021-02-08T17:18:29Z" duration-ms="523416" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid username expected [true] but found [false],
	MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid password expected [true] but found [false],
	Exception in Test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid username expected [true] but found [false],
	MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid password expected [true] but found [false],
	Exception in Test expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.trgr.quality.maf.tests.LoginTest.loginWithValidAndInvalidCredentials(LoginTest.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidAndInvalidCredentials -->
        <test-method signature="loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" started-at="2021-02-08T17:18:29Z" name="loginUsingSaveUserNameAndPwd" description="MAFQABANG-45" finished-at="2021-02-08T17:22:31Z" duration-ms="241841" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Exception in Test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Exception in Test expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.trgr.quality.maf.tests.LoginTest.loginUsingSaveUserNameAndPwd(LoginTest.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUsingSaveUserNameAndPwd -->
        <test-method signature="loginUsingSaveUserName()[pri:6, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" started-at="2021-02-08T17:22:31Z" name="loginUsingSaveUserName" description="MAFQABANG-42" finished-at="2021-02-08T17:26:32Z" duration-ms="240693" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	Exception in Test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	Exception in Test expected [true] but found [false]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.trgr.quality.maf.tests.LoginTest.loginUsingSaveUserName(LoginTest.java:432)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUsingSaveUserName -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" started-at="2021-02-08T17:26:32Z" name="afterClass" finished-at="2021-02-08T17:28:33Z" duration-ms="121246" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="driverclose()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@72035809]" started-at="2021-02-08T17:28:33Z" name="driverclose" finished-at="2021-02-08T17:28:34Z" duration-ms="574" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverclose -->
      </class> <!-- com.trgr.quality.maf.tests.LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- CHP TEST -->
</testng-results>
