<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="14" total="17" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-02-23T13:49:02 ART" name="CHP TEST" finished-at="2021-02-23T13:49:57 ART" duration-ms="54949">
    <groups>
      <group name="chppe">
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chppe -->
      <group name="chparg">
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chparg -->
      <group name="chpmex">
        <method signature="LoginTest.loginUsingSaveUserName()[pri:6, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginUsingSaveUserName" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chpmex -->
      <group name="chpchile">
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chpchile -->
      <group name="chpury">
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chpury -->
      <group name="chpbr">
        <method signature="LoginTest.loginUsingSaveUserName()[pri:6, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginUsingSaveUserName" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginUsingSaveUserNameAndPwd" class="com.trgr.quality.maf.tests.LoginTest"/>
        <method signature="LoginTest.loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" name="loginWithValidAndInvalidCredentials" class="com.trgr.quality.maf.tests.LoginTest"/>
      </group> <!-- chpbr -->
    </groups>
    <test started-at="2021-02-23T13:49:02 ART" name="LoginTest" finished-at="2021-02-23T13:49:57 ART" duration-ms="54949">
      <class name="com.trgr.quality.maf.tests.LoginTest">
        <test-method is-config="true" signature="setup(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" started-at="2021-02-23T13:48:57 ART" name="setup" finished-at="2021-02-23T13:49:02 ART" duration-ms="4297" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[prod]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chpbr]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" started-at="2021-02-23T13:49:02 ART" name="beforeClass" finished-at="2021-02-23T13:49:02 ART" duration-ms="14" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="loginWithValidAndInvalidCredentials()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" started-at="2021-02-23T13:49:02 ART" name="loginWithValidAndInvalidCredentials" description="MAFQABANG-32" finished-at="2021-02-23T13:49:57 ART" duration-ms="54822" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid username expected [true] but found [false],
MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid password expected [true] but found [false],
Exception in Test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid username expected [true] but found [false],
MAFQABANG-32:Login with valid and invalid credentails : Validated Login with invalid password expected [true] but found [false],
Exception in Test expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.trgr.quality.maf.tests.LoginTest.loginWithValidAndInvalidCredentials(LoginTest.java:123)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidAndInvalidCredentials -->
        <test-method signature="loginUsingSaveUserNameAndPwd()[pri:1, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" started-at="2021-02-23T13:49:57 ART" name="loginUsingSaveUserNameAndPwd" description="MAFQABANG-45" finished-at="2021-02-23T13:49:57 ART" duration-ms="25" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Exception in Test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Exception in Test expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.trgr.quality.maf.tests.LoginTest.loginUsingSaveUserNameAndPwd(LoginTest.java:218)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUsingSaveUserNameAndPwd -->
        <test-method signature="loginUsingSaveUserName()[pri:6, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" started-at="2021-02-23T13:49:57 ART" name="loginUsingSaveUserName" description="MAFQABANG-42" finished-at="2021-02-23T13:49:57 ART" duration-ms="20" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Exception in Test expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Exception in Test expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.trgr.quality.maf.tests.LoginTest.loginUsingSaveUserName(LoginTest.java:432)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginUsingSaveUserName -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" started-at="2021-02-23T13:49:57 ART" name="afterClass" finished-at="2021-02-23T13:49:57 ART" duration-ms="17" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method is-config="true" signature="driverclose()[pri:0, instance:com.trgr.quality.maf.tests.LoginTest@5ba3f27a]" started-at="2021-02-23T13:49:57 ART" name="driverclose" finished-at="2021-02-23T13:50:01 ART" duration-ms="4322" status="FAIL">
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[chrome not reachable
  (Session info: chrome=88.0.4324.182)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'TR-JDGMXY2', ip: '192.168.19.184', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '14.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.182, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: C:\Users\C275973\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:52050}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 1ffae3857eb65c15ba0d0e6aa0198241]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: chrome not reachable
  (Session info: chrome=88.0.4324.182)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'TR-JDGMXY2', ip: '192.168.19.184', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '14.0.2'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.182, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: C:\Users\C275973\AppData\Lo...}, goog:chromeOptions: {debuggerAddress: localhost:52050}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 1ffae3857eb65c15ba0d0e6aa0198241
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
at org.openqa.selenium.remote.RemoteWebDriver.close(RemoteWebDriver.java:442)
at com.trgr.quality.maf.webdriver.WebDriverFactory.removedriver(WebDriverFactory.java:175)
at com.trgr.quality.maf.basetest.BaseTest.driverclose(BaseTest.java:663)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:351)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- driverclose -->
      </class> <!-- com.trgr.quality.maf.tests.LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- CHP TEST -->
</testng-results>
